# -*- coding: utf-8 -*-
"""Data Generation using Modelling and Simulation for Machine Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XbzZ66ikFTyhxlb_cWKVSk7iroHhtior
"""

pip install cantera

import cantera as ct
print(ct.__version__)

# ===============================
# 1. Install and Import Cantera
# ===============================
!pip install cantera

import cantera as ct
import numpy as np
import pandas as pd

print("Cantera Version:", ct.__version__)


# ===============================
# 2. Load Chemical Mechanism
# ===============================
gas = ct.Solution("gri30.yaml")

print("\n--- Simulator Information ---")
print("Number of species:", gas.n_species)
print("Number of reactions:", gas.n_reactions)
print("Sample species:", gas.species_names[:5])


# ===============================
# 3. Identify Parameters
# ===============================
print("\n--- Simulator Parameters ---")
print("Temperature unit: Kelvin (K)")
print("Pressure unit: Pascal (Pa)")

# Set default state
gas.TP = 300, ct.one_atm
print("Default Temperature (K):", gas.T)
print("Default Pressure (Pa):", gas.P)


# ===============================
# 4. Reaction of Interest
# ===============================
print("\n--- Reaction Output Parameter ---")
nh3_index = gas.species_index("NH3")
print("NH3 species index:", nh3_index)

print("NH3 production rate at default state:",
      gas.net_production_rates[nh3_index])


# ===============================
# 5. Parameter Bounds
# ===============================
TEMP_MIN, TEMP_MAX = -40, 40     # Celsius
PRESS_MIN, PRESS_MAX = 10, 50    # atm

print("\n--- Parameter Bounds ---")
print("Temperature (°C):", TEMP_MIN, "to", TEMP_MAX)
print("Pressure (atm):", PRESS_MIN, "to", PRESS_MAX)


# ===============================
# 6. Generate Simulation Data
# ===============================
records = []

for _ in range(1000):
    T_c = np.random.uniform(TEMP_MIN, TEMP_MAX)
    P_atm = np.random.uniform(PRESS_MIN, PRESS_MAX)

    gas.TP = T_c + 273.15, P_atm * ct.one_atm
    rate = abs(gas.net_production_rates[nh3_index])

    records.append([T_c, P_atm, rate])

df = pd.DataFrame(
    records,
    columns=["Temperature_C", "Pressure_atm", "Reaction_Rate"]
)

print("\n--- Sample Output Data ---")
print(df.head())


# ===============================
# 7. Save Dataset
# ===============================
df.to_csv("cantera_simulated_data.csv", index=False)
print("\nDataset saved as cantera_simulated_data.csv")

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

import pandas as pd

# Assume df already exists with columns:
# Temperature_C, Pressure_atm, Reaction_Rate

X = df[["Temperature_C", "Pressure_atm"]]
y = df["Reaction_Rate"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(n_estimators=100),
    "Support Vector Regression": SVR(),
    "KNN": KNeighborsRegressor()
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    results.append([name, mse, r2])

results_df = pd.DataFrame(
    results, columns=["Model", "MSE", "R2 Score"]
)

print(results_df)